### PR TITLE
Create bare bones Django app

### LINKED ISSUE #1: CNVGR-1 Create the app bare bones!
This ticket blocks all others!

Django (will update and change to Flask if community denotes otherwise, but Django comes with a lot of features out of the box and will help)

We're choosing to use python for this project due to the accessibility and DX. Our community is also more familiar with Python.

Create the application and push the starter code to this repo. That's it. 🥳

### PR DESCRIPTION
**Pull request by KristinJJ**
Closes #1 

# Description 
Creates the bare bones of the Django app. As a User, I want to be able to see the app when I go to a specific address.
Screen Shot 2021-10-19 at 3 55 54 PM

# Tested
Chrome browser on macOS (Big Sur)

# Testing
- [x] Download and install Python3 3.8.5
- [x] Run `pip3 install pipenv` in the terminal to manage dependencies
- [x] Run `pip3 install django` in the terminal to install Django
- [x] For whichever IDE you're using, install whichever Python extensions are needed to run Python code
- [x] Clone project to your computer using `git clone https://github.com/NSC-Computer-Science-Club/converger_app.git` in the terminal
- [x] Run `pipenv --venv` in the terminal to look for the path to the Python virtual environment on your local computer
  - [ ] If you get an error `pipenv not found` try running `sudo -H pip install -U pipenv`
  - [ ] It should look something like `/Users/kristinjue/.local/share/virtualenvs/converger_app-8tyBun2h`
  - [ ] In VSCode on macOS, find `Select Python Interpreter` by using `Shift-Command-p`
  - [ ] Enter the terminal path and add to the end `/bin/activate`, so it looks something like `/Users/kristinjue/.local/share/virtualenvs/converger_app-8tyBun2h/bin/activate`
  - [ ] In the .vscode folder, replace `/Users/kristinjue/.local/share/virtualenvs/converger_app-8tyBun2h/bin/activate` with the path to the virtual environment on your local machine.
- [x] Run `python3 manage.py runserver`
- [x] Django web app should open at location `http://127.0.0.1:8000/`
- [ ] If you see a warning about unapplied migrations, like  `You have unapplied migrations; your app may not work properly until they are applied.
Run 'python3 manage.py migrate' to apply them.` you can ignore them for now, unless you want to run the migrate command just in case.
- [x] Quit the server by either closing the terminal window or running `Control C` on macOS

### CODE REVIEW

**Review by ReneCapella — DISMISSED** [review]
Whoo 🎉 app started whooo

Adjusted branches, merging feature to release_candidate. Only release_candidate merges to main.

**Comment by KristinJJ** [comment]
Added the testing steps, and converted to non-draft. Please review by following the testing steps and verify the app works!

**Review by ReneCapella — COMMENTED** [review]
Really nice testing experience. I've never had anyone give such detailed steps for set up. 

ran into a few blockers
-`pipenv --venv `//pipenv not found, needed to run `sudo -H pip install -U pipenv` to resolve
then
-`pipenv --venv` //`"No virtualenv has been created for this project(<path here>)Aborted!` 
-- solved by `pipenv install django`

I don't use VS Code, so I'm not sure if any of that is necessary, but could check for atom or other IDEs
but when I ran `python manage.py`, I got:
```
File "manage.py", line 17
    ) from exc
         ^
SyntaxError: invalid syntax
```
so looking into this and seeing if the path instructions for VSCode (mapped to my own IDEs) could be the source.

**Comment by KristinJJ** [comment]
> Really nice testing.
> 
> ran into a few blockers
> 
> * pipenv --venv //pipenv not found, needed to run `sudo -H pip install -U pipenv` to resolve
>   then
>   -pipenv --venv //"No virtualenv has been created for this project()Aborted!
> 
> still working on resolving this one.

I think I might know what the "No virtualenv has been created for this project()Aborted!" might be about, might need to run `python manage.py runserver` before running `pipenv --venv` to get the path for the virtual server?

**Review by ReneCapella — APPROVED** [review]
Awesome awesome testing experience. Ironed out some spots, but it's running great.

**Comment by KristinJJ** [comment]
> Really nice testing experience. I've never had anyone give such detailed steps for set up.
> 
> ran into a few blockers -`pipenv --venv `//pipenv not found, needed to run `sudo -H pip install -U pipenv` to resolve then -`pipenv --venv` //`"No virtualenv has been created for this project(<path here>)Aborted!` -- solved by `pipenv install django`
> 
> I don't use VS Code, so I'm not sure if any of that is necessary, but could check for atom or other IDEs but when I ran `python manage.py`, I got:
> 
> ```
> File "manage.py", line 17
>     ) from exc
>          ^
> SyntaxError: invalid syntax
> ```
> 
> so looking into this and seeing if the path instructions for VSCode (mapped to my own IDEs) could be the source.

Thanks for this thorough review! Updated testing steps to include revisions

**Pull request merged**
